discord:
  client_token: ODQzMTMzOTY5OTM1NzYxNDI4.YJ_bsw.Sm3beRCuY_ZCYZXgFthlebmOKVQ
twitter:
  bearer: AAAAAAAAAAAAAAAAAAAAAK6yPgEAAAAAT1yaXbs9II3eUoVnke7KpmVFKBI%3DdU9prVHy1ahBL0ZubzrNHlbTvOP5GLlhZBVXGSEfNy8W9FTXJB
  apiKey: XXRtnvNOBZh0KZw4p32TpWsWO
  apiSecret: ia3NoMRV4hsGXtVBafxsj269T97Uy5v1X6CPkdprjkgguxrIiS